[tool.ruff]
exclude = [
    # This code is outdated, but I keep it there for now
    "kde",
    # This is vendored code
    "deveba/shell.py"
]

[tool.ruff.lint]
select = [
    # pycodestyle
    "E",
    # pyflakes
    "F",
    # pyupgrade
    "UP",
    # bugbear
    "B",
]
